# Generated by Django 5.1.3 on 2025-08-18 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('havasbook', '0026_bookmodel_description_en_bookmodel_name_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='reciever_userName',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Username'),
        ),
    ]
