# Generated by Django 5.1.3 on 2025-08-23 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('havasbook', '0027_ordermodel_reciever_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brandmodel',
            name='category',
        ),
        migrations.AddField(
            model_name='brandmodel',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='havasbook.categorymodel', verbose_name='Категория'),
        ),
    ]
