# Generated by Django 5.1.3 on 2025-08-23 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('havasbook', '0028_remove_brandmodel_category_brandmodel_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandmodel',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='brands', to='havasbook.categorymodel', verbose_name='Категория'),
        ),
        migrations.RemoveField(
            model_name='brandmodel',
            name='category',
        ),
        migrations.AddField(
            model_name='brandmodel',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_brands', to='havasbook.categorymodel', verbose_name='Категория'),
        ),
    ]
