# Generated by Django 5.1.3 on 2025-08-27 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('havasbook', '0029_brandmodel_categories_remove_brandmodel_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandmodel',
            name='has_products',
            field=models.BooleanField(default=False, verbose_name='Mahsulot borligi'),
        ),
    ]
