# Generated by Django 5.1.3 on 2025-08-27 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('havasbook', '0030_brandmodel_has_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='havasbook.brandmodel', verbose_name='Бренд'),
        ),
    ]
