# Generated by Django 5.1.3 on 2025-08-27 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('havasbook', '0031_alter_bookmodel_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandmodel',
            name='subcategories',
            field=models.ManyToManyField(blank=True, related_name='brands', to='havasbook.subcategorymodel'),
        ),
    ]
