# Generated by Django 5.1.3 on 2025-09-11 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('havasbook', '0032_brandmodel_subcategories'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannermodel',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Link'),
        ),
    ]
