# Generated by Django 5.1.3 on 2025-09-17 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('havasbook', '0033_bannermodel_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildcategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='havasbook.subcategorymodel')),
            ],
            options={
                'verbose_name': 'ChildcategoryModel',
                'verbose_name_plural': 'ChildcategoryModels',
                'db_table': 'ChildCategory',
            },
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='childcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='havasbook.childcategorymodel'),
        ),
    ]
