# Generated by Django 5.1.3 on 2025-09-17 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('havasbook', '0034_childcategorymodel_bookmodel_childcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='childcategorymodel',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='childcategorymodel',
            name='title_kril',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='childcategorymodel',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='childcategorymodel',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
    ]
