# Generated by Django 5.1.3 on 2025-09-17 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('havasbook', '0035_childcategorymodel_title_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmodel',
            name='childcategory',
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='childcategories',
            field=models.ManyToManyField(blank=True, related_name='products', to='havasbook.childcategorymodel'),
        ),
    ]
