# Generated by Django 5.1.3 on 2025-09-17 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('havasbook', '0036_remove_bookmodel_childcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategorymodel',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='subcategorymodel',
            name='name_kril',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='subcategorymodel',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='subcategorymodel',
            name='name_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='childcategories',
            field=models.ManyToManyField(blank=True, related_name='products', to='havasbook.childcategorymodel', verbose_name='Дочерние категории'),
        ),
    ]
